---
title: "Results Section Three"
description: "Composite Vulnerability Index"
tags: ["R", "networks"]
weight: 4
draft: false
output: html_document
---

## Main Findings 
###Factor Analysis


###Composite Vulnerability Score
Page county is a rural county in the Valley region in Virginia. While factor analysis and composite index construction have been done on different scales, we are limited by our data to the county level. However, other social and economic modeling approaches were applied to county level data and were developed to address short comings of predecessor models (Cutter et al., 2003).  
 
The social and economic vulnerability index (SEVI) is constructed using county level data on poverty rate, ethnicity, spoken language, physical and mental disabilities, housing type, incarceration rates, drug arrest rates and access to private/public transportation. All of these factors can affect the level of vulnerability in a county.  The formula for the SEVI was created as:

Our model uses a varimax rotation with the maximum likelihood solution method. Using the correlations with the unobserved factors, we use the following formula to construct the composite vulnerability scores.

$$\mathcal{F} = (X^s\centerdot F^T) \centerdot \textbf{w}$$

where $\mathcal{F}$ is the Composite Score, 
$X^s$ is the Standardized design matrix, $F^T$ is the Matrix of Factor Scores and $\textbf{w}$ is the Proportion of Variance Explained.

The SEVI is shown in Figure 3 where lighter colors represent more vulnerable populations. The map shows that across NOVA, and even within Loudon County, there are important differences in social and economic vulnerability. Socially and economically vulnerable areas are often located close to areas with low vulnerability. However, the SEVI is only one side of the food insecurity story. Food insecurity is also affected by access to food in the local area. Nonetheless, the SEVI provides a means of assessing areas that may be in need of targeted assistance. 
### Conclusion and Policy Implications 

[Here you could highlight the main takeaways and the potential policy implications of your findings.] 

### References 

[List your references here using APA format (or at least standardize all of the references using the same format).]